### ISSUE TITLE
useCheckoutPricing hook is not found in the package.

### ISSUE THREAD

**Issue by babulal-gaxon** [recurly/react-recurly#36]
Hi tried to run your demo for checkout-pricing.js. But getting error 

TypeError: Object(...) is not a function

CheckoutPricingForm
react-recurly/demo/src/checkout-pricing.js:14

Could you please help us to resolve this issue.

**Comment by dbrudner** [comment]
Good call out!

The issue here is that the `<CheckoutPricing />` component in the demo is looking for `useCheckoutPricing` in `@react/recurly`, but `useCheckoutPricing` hasn't been released to NPM yet, although it's on the master branch.

A temporary workaround would be to remove `<CheckoutPricing />` from the demo.

This issue will be fixed when `useCheckoutPricing` goes out with our next release, which should be happening in the next few days.

I'm going to close the issue, but feel free to add additional comments or questions if needed.

**Comment by ashokdudhade-cbs** [comment]
When will be new version released?

**Comment by dbrudner** [comment]
@ashokdudhade-cbs We just released it moments ago! The demo should be fixed now. Thanks again for reporting.
